Feat/ehorn/telephone validator
in-ventures/components pull request #31
Opened 2020-08-21 00:05 UTC by pita-horn

# Description
Se incorporan el componente de PhoneInput para ingreso de teléfono. Se crea en conjunto con los validadores LengthValidator y NumericValidadores para comprobar que el largo del teléfono es el correcto para el país seleccionado y que se han ingresado sólo números. El validador adapta el mensaje de error para mostrar cuántos dígitos el usuario se ha pasado o le faltan.

InputForPhone recibe props del tipo InputforPhoneProps que se están manejando a través de un dummy para la etapa de desarrollo y testeo. Se debe eliminar luego de ser aprobada la PR.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New component (non-breaking change which adds component)
- [x] New hook (non-breaking change which adds hook)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Maintenance (repo config)
- [ ] Documentation

## How Has This Been Tested?

- [x] Storybook
- [ ] Unit testing

### Screenshots (Only if need)
![PhoneInput](https://user-images.githubusercontent.com/26127375/90837488-2d7f5680-e320-11ea-93d8-ea5d3e2cb26a.PNG)

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] The target of this commit is 'dev'
- [ ] Any dependent changes have been merged and published in downstream modules

2020-08-21 13:10 UTC, farojos commented on src/hooks/validators/PhoneValidator.ts
> +    //this.countryDigits = countryDigits;
Commented code

2020-08-21 13:19 UTC, pitahorn commented on src/hooks/validators/PhoneValidator.ts
> +    //this.countryDigits = countryDigits;
Gracias! Fixed 🔧

2020-08-24 20:45 UTC, gsulloa requested changes

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/formatters/index.ts
> +export { LatinFormatter, LatinEmailFormatter } from './LatinFormatter';
Solo existe LatinEmailFormatter

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/useInput.hooks.ts
> +  maxLength?: number;
eliminar maxLength

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/useInput.hooks.ts
> +  const [length, setLength] = useState<number | undefined>(options.maxLength);
eliminar

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/useInput.hooks.ts
> +          validator.validate(newValue, length) ? '' : validator.errorMsg,
solo entregar newValue

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/useInput.hooks.ts
> +      length,
eliminar

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/useInput.hooks.ts
> +    // todo validate if bit now can use elvis operator to avoid this mess
eliminar, no era la razón

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/useInput.hooks.ts
> +  const updateMaxLength = useCallback(
eliminar

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/useInput.hooks.ts
> +  // todo - gabo to explain usememo hook
useMemo calcula un valor usando la función entregada, cada vez que las dependencias cambien. Si no cambian, se vuelve a usar el mismo valor anterior y no se recomputa

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/useInput.hooks.ts
> +    updateMaxLength,
eliminar

2020-08-24 20:45 UTC, gsulloa commented on src/hooks/validators/LengthValidator.ts
> +  maxLength: number;
no sería maxLength, sería requiredLength o similar

2020-08-24 20:45 UTC, gsulloa commented on src/stories/1-Input.stories.tsx
> +    //maxLength: country.countryDigitLength,
eliminar

2020-08-24 20:45 UTC, gsulloa commented on src/stories/1-Input.stories.tsx
> +      updateMaxLength(newCountry.countryDigitLength);
eliminar

2020-08-24 21:37 UTC, pita-horn commented on src/hooks/useInput.hooks.ts
> +  // todo - gabo to explain usememo hook
👌👌👌

2020-08-25 01:15 UTC, mario-merino requested changes

2020-08-25 01:15 UTC, mario-merino commented on src/hooks/validators/LengthValidator.ts
> +}
@pita-horn @gsulloa nos faltó ver como este validador podria tambien ayudar para el largo del rut, para eso creo que tomaria un minLegth y un maxLength y que le validador vea si esta entre el rango. y se lo agregaria a al stoprybook del rut para evitar los casos en que es 1.111-1

2020-08-25 01:15 UTC, mario-merino commented on src/hooks/formatters/LatinFormatter.ts
> +export const LatinEmailFormatter = (input: string) => {
@pita-horn no es latin realmente ni solo para email, diria que es un accentRemover

2020-08-25 01:15 UTC, mario-merino commented on src/hooks/validators/Validator.ts
> +  validate(input: T, extra?: any) {
@pita-horn extra ya no sería necesario, no?

2020-08-25 03:36 UTC, mario-merino reviewed
@pita-horn me da la impresión que se perdió aquí el te faltan/sobran n dígitos, no?

2020-08-25 03:36 UTC, mario-merino commented on src/hooks/formatters/LatinFormatter.ts
> +export const LatinEmailFormatter = (input: string) => {
@gsulloa la idea no es ir construyendo como extand de la clase formatter?

2020-08-25 03:36 UTC, mario-merino commented on src/hooks/formatters/Formatter.ts
> +        throw new Error('validate is not implemented');
@pita-horn  validate or format?

2020-08-25 20:32 UTC, gsulloa approved these changes

2020-08-25 20:32 UTC, gsulloa approved these changes

2020-08-25 20:33 UTC, merged