Feat/greg/loadimage
in-ventures/components pull request #72
Opened 2020-09-04 18:11 UTC by LilCore

# Description

Please include a description of the changes and relevant information. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New component (non-breaking change which adds component)
- [ ] New hook (non-breaking change which adds hook)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Maintenance (repo config)
- [ ] Documentation

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x ] Storybook
- [ ] Unit testing

### Screenshots (Only if need)

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] The target of this commit is 'dev'
- [ ] Any dependent changes have been merged and published in downstream modules

2020-09-04 18:55 UTC, gsulloa requested changes
Además de los comentarios, arreglar los conflictos

2020-09-04 18:55 UTC, gsulloa commented on src/components/ImageLoader.tsx
> +                    alt="Medicamento"
dejar alt en las props, que no esté hardcodeado

2020-09-04 18:55 UTC, gsulloa commented on src/stories/4-imageloeader.stories.tsx
> +            <ImageLoader
La idea es que el componente reciba por props imagesrc y setImagesrc, y que internamente haga el manejo de `URL.createObjectURL`. Que el componente padre le pase directamente lo del useState solamente

2020-09-07 13:38 UTC, gsulloa commented
Para arreglar tests correrlos en local con `yarn test`
Para arreglar la mayoría de los errores de lint, correr en local `yarn lint:fix`. Luego arreglar manual los errores que queden

2020-09-07 14:32 UTC, LilCore commented
> Para arreglar tests correrlos en local con `yarn test`
> Para arreglar la mayoría de los errores de lint, correr en local `yarn lint:fix`. Luego arreglar manual los errores que queden

 Tengo un error de yarn test de algo que no hice yo, "Failed prop type: The prop `justify` of `Grid` must be used on `container`" en el componente ProductCard

En yarn lint:fix ya arregle los errores, solo me sale una advertencia en MaskFormatter.ts

2020-09-07 15:49 UTC, gsulloa commented
> > Para arreglar tests correrlos en local con `yarn test`
> > Para arreglar la mayoría de los errores de lint, correr en local `yarn lint:fix`. Luego arreglar manual los errores que queden
> 
> Tengo un error de yarn test de algo que no hice yo, "Failed prop type: The prop `justify` of `Grid` must be used on `container`" en el componente ProductCard
> 
> En yarn lint:fix ya arregle los errores, solo me sale una advertencia en MaskFormatter.ts

Perfect!

Ese fue un warning que se origino en otro PR que paso antes de agregar las validaciones, no hay problema 👌

2020-09-08 00:30 UTC, coniurzua commented
@LilCore creo que queda mejor con object-fit: contain una vez que se "sube" la imagen

2020-09-08 12:29 UTC, mario-merino commented
@LilCore ojo el manejo de pdf, le voy a pedir a la maida que suba el diseño

2020-09-08 13:17 UTC, LilCore commented
> object-fit: contain

![eeee](https://user-images.githubusercontent.com/18475247/92481218-07790380-f1b4-11ea-9de5-e4a0489ec435.png)

Se ve así @coniurzua

2020-09-08 13:27 UTC, LilCore commented
> @LilCore ojo el manejo de pdf, le voy a pedir a la maida que suba el diseño

Cómo es esto?, debería salir contenido del PDF en el recuadro? la primera página?

2020-09-08 20:57 UTC, gsulloa commented
Arreglar:
- Lint
- tests
- Deja subir mayores del peso permitido

2020-09-08 22:10 UTC, mario-merino commented
@LilCore diría que sea clickeable todo el cuadrado

2020-09-09 19:32 UTC, mario-merino requested changes

2020-09-09 19:32 UTC, mario-merino commented on src/assets/imageloader.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
@LilCore este ya no es necesario, no?

2020-09-09 19:32 UTC, mario-merino commented on src/components/ImageLoader.tsx
> +        if (file.size / divisor <= maxFileSize) {
@LilCore no vendría la compresión antes de entrar a ver el tamaño resultante?

2020-09-09 19:32 UTC, mario-merino commented on src/components/ImageLoader.tsx
> +        imgs[0].style.objectFit = objectFit ? objectFit : '';
@LilCore dejaría contain como defecto si no viene la prop

2020-09-09 19:32 UTC, mario-merino commented on src/stories/4-imageloeader.stories.tsx
> +
@LilCore como dijo gabo, agrega un knob para mostrar el porcentaje de avance y loading true/false

2020-09-09 19:32 UTC, mario-merino commented on src/components/ImageLoader.tsx
> +        {loading ? <LinearProgress variant="determinate" value={10} /> : ''}
@LilCore aquí deberia tomar el porcentaje de avance como prop, ya que el padre lo va a actualizar según como progressa la subida y respuesta del backend

2020-09-09 19:32 UTC, mario-merino commented on src/components/ImageLoader.tsx
> +  container: {
@LilCore fijate que el iframe agrega un borde raro, creo que hay que ponerle al CSS `border: none;`

2020-09-09 19:32 UTC, mario-merino commented on src/components/ImageLoader.tsx
> +        if (file.size / divisor <= maxFileSize) {
@gsulloa pondrías como prop opcional la compresión o lo aplicamos siempre?

2020-09-09 19:33 UTC, mario-merino commented on src/stories/4-imageloeader.stories.tsx
> +export const Base = () => {
@LilCore le pondría nombre "portrait" a esta y "landscape" a la otra, detalle minimo

2020-09-09 19:42 UTC, LilCore commented on src/components/ImageLoader.tsx
> +        if (file.size / divisor <= maxFileSize) {
Sí

2020-09-09 19:52 UTC, LilCore commented on src/components/ImageLoader.tsx
> +        if (file.size / divisor <= maxFileSize) {
Bueno, sería cuestion de ver el tamaño primero, si excede y es imagen se comprime, si excede y no es imagen arroja error y si no excede no comprime

2020-09-15 13:00 UTC, mario-merino approved these changes

2020-09-15 16:58 UTC, mario-merino requested changes

2020-09-15 16:58 UTC, mario-merino commented on src/components/ImageLoader.tsx
> +            />
A poner loading, la imagen que quiero subir no se ve, la idea es mostrarla pero con opacidad
Pondría siempre el loader (pero inicialmente en 0) para que no distorsione el alto
Usaría clsx para evitar repeticion de css (mira como lo usamos en el card)
dejaría el alto de la imagin como el calc(100% - 52px)
action area pondria 0 padding
botones icon podria margen izquierda y derecha para que queden centrado
investigaria porque la imagen le hace un rezise solo despues de hacer click, dudo si el hook esta implementado correctamente

2020-09-15 17:13 UTC, mario-merino commented on src/components/ImageLoader.tsx
> +  setProgress = () => {},
que hace esto? veo que no hace nada

2020-09-15 20:08 UTC, gsulloa commented
Cerrando con como va. Los arreglos que falten se podrán ver en https://github.com/in-ventures/react-lib/issues/100

2020-09-15 20:08 UTC, merged