fix of text colors and buttons form, add of extra button
in-ventures/components pull request #90
Opened 2020-09-11 14:48 UTC by LilCore

# Description

Please include a description of the changes and relevant information. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New component (non-breaking change which adds component)
- [ ] New hook (non-breaking change which adds hook)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Maintenance (repo config)
- [ ] Documentation

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x ] Storybook
- [ ] Unit testing

### Screenshots (Only if need)

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] The target of this commit is 'dev'
- [x ] Any dependent changes have been merged and published in downstream modules

2020-09-11 15:47 UTC, gsulloa approved these changes

2020-09-14 14:46 UTC, coniurzua commented
Hola! Se ve bastante bien!
Sólo un par de comentarios:
1. Podríamos dejar el chip de receta simple o retenida con "border-radius: 4px"
2. El color del nombre comercial y la dosis deberían ir en "#text-primary-414046"
3. Podríamos probar cómo quedaría con el nombre comercial más grande o en bold?

Gracias!

2020-09-14 16:09 UTC, coniurzua requested changes
Hola! Se ve bastante bien!
Sólo un par de comentarios:
1. Podríamos dejar el chip de receta simple o retenida con "border-radius: 4px"
2. El color del nombre comercial y la dosis deberían ir en "#text-primary-414046"
3. Podríamos probar cómo quedaría con el nombre comercial en bold?

Gracias!

2020-09-14 18:51 UTC, LilCore commented
> 2\. mbre comercial y la dosis deberían ir en "#text-primary-414046"

Hola,

Le cambié el radio del chip a 4px y le subí el tamaño al texto del nombre comercial a 13px con la clase subtitle1 como dice en Zeplin. Con respecto al color del texto del nombre comercial y del valor unitario ya este estaba fijado en primary.

2020-09-15 17:24 UTC, merged